name: Deploy Extension

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to (e.g., v1.0.0)'
        required: false
        default: ''

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || 'main' }}
          fetch-depth: '0'
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - run: npm ci

      - name: Bump version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if [ -n "${{ github.event.inputs.version }}" ]; then
            npm version ${{ github.event.inputs.version }}
          else
            npm version patch
          fi
          git push origin HEAD:main --follow-tags

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: false
          skipDuplicate: false